from modules.cwt import ContinuousWaveletTransform
from modules.self_supervised import SelfSupervisedLoss, TimeContrastiveAugmentation, FreqContrastiveAugmentation
from modules.teacher_model import TeacherModel, PseudoLabelGenerator
from modules.multi_adversarial import MultiAdversarialLoss, DomainAdversarialTrainer